version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db

  mysql-db:
    image: "mysql:5.7"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rest_api_db
      MYSQL_USER: user1
      MYSQL_PASSWORD: user-pw
      MYSQL_ROOT_PASSWORD: root
